
#include <stdio.h>
#include <iostream>
#include "OriReader.h"


int main()
{
	std::string Ori = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTT\
GTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTC\
AGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCA\
TCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCA\
ATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC";

	std::string Pattern = "TGATCA";

	OriReader* m_OriReader = new OriReader();

	std::cout << m_OriReader->PatternCount(Ori, Pattern) << std::endl;

	m_OriReader->GenerateFrequencyMap(Ori, 9);

	//m_OriReader->PrintFrequencyMap();

	m_OriReader->FindMostFrequentWord();

	delete m_OriReader;
	system("PAUSE");
	return 0;
}