
#include <stdio.h>
#include <iostream>
//#include <memory>

#include "OriReader.h"


void printFrequencyMap() {
	std::unique_ptr<OriReader::FrequencyMap> frequencyMap = OriReader::GenerateFrequencyMap("CGATATATCCATAG", 3);
	for (auto word = frequencyMap.get()->begin(); word != frequencyMap.get()->end(); ++word)
	{
		std::cout << word->first << "  " << word->second << std::endl;
	}
}

int main()
{
	std::string Ori = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTT\
GTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTC\
AGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCA\
TCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCA\
ATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC";

	std::string Pattern = "TGATCA";

	std::cout << OriReader::PatternCount(Ori, Pattern) << std::endl;

	printFrequencyMap();

	system("PAUSE");
	return 0;
}